services:
  api-service:
    build: ./api-service
    env_file: .env.${NODE_ENV}
    init: true
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - redis
    networks:
      - d-platform-network

  messaging-service:
    build: ./messaging-service
    env_file: .env.${NODE_ENV}
    init: true
    ports:
      - "3001:3001"
    depends_on:
      - redis
    networks:
      - d-platform-network

  map-service:
    build: ./map-service
    ports:
      - "3003:3003"
    networks:
      - d-platform-network

  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
      - ./certs:/etc/livekit
    restart: always
    env_file: .env.${NODE_ENV}
    ports:
      - "7880:7880"
      - "7881:7881"
      - "40000-40050:40000-40050/udp"
    networks:
      - d-platform-network


  nginx:
    image: nginx:alpine
    volumes:
      - ./${NGINX_CONF:-nginx.local.conf}:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - d-platform-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    networks:
      - d-platform-network

networks:
  d-platform-network:
    driver: bridge
