services:
  api-service:
    build: ./api-service
    env_file: .env
    init: true
    ports:
      - "5000:3000"
    depends_on:
      - redis
    networks:
      - d-platform-network

  messaging-service:
    build: ./messaging-service
    env_file: .env
    init: true
    ports:
      - "3001:3001"
    depends_on:
      - redis
    networks:
      - d-platform-network

  map-service:
    build: ./map-service
    ports:
      - "3003:3003"
    networks:
      - d-platform-network

  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    network_mode: host
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
      - ./certs:/etc/livekit
    restart: always
    env_file: .env

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - d-platform-network

  redis:
    image: redis:alpine
    networks:
      - d-platform-network

networks:
  d-platform-network:
    driver: bridge